AllCops:
  Exclude:
    - bin/*
    - config/**/*
    - db/schema.rb
    - db/seeds.rb
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - lib/tasks/auto_annotate_models.rake
    - Gemfile
    - Guardfile
  # By default, the rails cops are not run. Override in project or home
  # directory .rubocop.yml files, or by giving the -R/--rails option.
  RunRailsCops: true
  # Cop names are not displayed in offense messages by default. Change behavior
  # by overriding DisplayCopNames, or by giving the -D/--display-cop-names
  # option.
  DisplayCopNames: true
  # Style guide URLs are not displayed in offense messages by default. Change
  # behavior by overriding DisplayStyleGuide, or by giving the
  # -S/--display-style-guide option.
  DisplayStyleGuide: true
  # Additional cops that do not reference a style guide rule may be enabled by
  # default. Change behavior by overriding StyleGuideCopsOnly, or by giving
  # the --only-guide-cops option.
  StyleGuideCopsOnly: true

Metrics/LineLength:
  Enabled: false
